import os

with open('src/main/scala/stdlib.wach') as f:
    stdlib = f.read()

with open('src/main/scala/StandardLib.scala', 'w') as f:
    f.write('''
/*

DO NOT EDIT THIS FILE, IT WILL BE AUTOGENERATED

*/

package object StandardLib {
    val STDLIB: String = """
''' + stdlib + '''
"""
}
''')